### ISSUE TITLE
Add componentType for making an array of components

### ISSUE THREAD

**Issue by zach-freyja** [Stuhl/javascript-entity-component-system#6]
Hi there. I'm that guy from Reddit who was gonna use this library. I liked it! I made some changes that I have in a PR for you if you want to add me to the repo. The main thing is I added a `componentType` to the component object. The motivation for this was the following:

The current code, as exemplified in your example, requires you to add the component, create an entity, then get the entity's component, and update its values if you want components with different start values. I want to be able to randomize starting state when I create the component, and not have to call getEntityComponents after creating the entity:

```javascript
positionComponents.push({
        name : "position" + Math.floor(Math.random() * 1000),
        componentType: 'position',
        state: {
          x: Math.floor(Math.random() * viewport.width),
          y: (viewport.height - 250) - (Math.floor(Math.random() * 100))
        }
      });
```

This change preserves existing behavior, and enables the randomization on creation behavior. The unique names in that example also makes it easy to remove components. The unique name can then be used when you call `createEntity` so that if you want to remove a specific entity you can find it by name.

I changed 'mass' to 'physics' in your example, and added acceleration to make it more explicit what was going on, as I think that'll be more familiar to people who have used ECSs before. 

I also removed some of the files from the top level that seemed to just be old builds.

I didn't make these changes, but I can if you like them:
* I'd change from parcel to webpack. Parcel adds a bunch of parcelly stuff and created a 22k line file when I tried to use it. Webpack generated a nice min file with no extra cruft
* I'd move all your example stuff to the top level and out of src. I'd also remove any files you're not using. Leaving them there seems sketch. 

Overall good work on this. I was up and running quickly and it was fun to use. Here's what I made with it:

https://github.com/Stuhl/javascript-entity-component-system/assets/42008305/36763665-7008-4231-a496-51e587191a80

**Comment by Stuhl** [comment]
Hello,

First of all thanks for using the lib and replying here. Didn't think I get a response this detailed.

I understand why you added the componentType property but it doesn't seem like a missing functionality thing but rather a easier way to change initial values. I would like to have a look on your PR to see how this looks in code. Generally I'm positive to implement this but I'd have to think about pro and cons about this approach. It sounds stupid but adding 1 more line to the component definition (and making 10-20 components) can add annoyance to the syntax. That said, if this reveals more usability problems, I would consider to change more than just the proposed change.

My goal here was to make it flexible and somewhat simple via compositon but leave the rest to the user. It's such a small library that I didn't even implement an auto ID increment for entities.

Regarding the rest, I'm happy for the tutorial change and the deletion of the files. They were redundant anyways, I was just too lazy to remove them.

I would stick to parcel though, I think I have a wrong setup. Normally it would generate a .min file too.

And nice program you made, mind showing the source? Could be used as a tutorial/show off

Cheers

**Comment by zach-freyja** [comment]
Happy to post the PR you just need to give me access. Also, another way to do what I want would be to be able to pass components along with component names in the component array for an entity. That would keep from adding another property on the type. If that sounds better to you I can submit a pr that way.

As for the program, I'm happy to share it. Just need to clean up the spaghetti that it's written in currently.

Also, where I'm going with this is adding a physics engine on top, and eventually a spell crafting system for a browser extension game. If you're not down to change it here, I'll just abstract it higher up the stack so no big deal.

**Comment by zach-freyja** [comment]
Oh wait the component passing doesn't work because then you have to make unique processors for everything. That's why I added the prop since ideally I can reuse the processor for a bunch of random components.

**Comment by Stuhl** [comment]
I sent you an invite.

We can discuss things further in the PR.
