### ISSUE TITLE
Array component

### ISSUE THREAD

**Issue by mckenytech** [Stuhl/javascript-entity-component-system#9]
i want to share how i made the create Entity accept array of component instead of string...its in react native tho

`
  const Pos=(x: number, y: number)=> ({
    
      name: CompName.POSITION,
      state:{
        x: makeMutable(x),
          y: makeMutable(y),
          isGrounded: makeMutable(false),
      },
    
  })
  const Area = (x: number, y: number, width: number, height: number):AreaState => ({
    name: CompName.AREA,
    state: {
     
      width: makeMutable(width),
      height: makeMutable(height),
    },
  });
  const Mass = (vX: number, vY: number):MassState => ({
    name: CompName.MASS,
    state: {
      vX: makeMutable(vX),
      vY: makeMutable(vY),
    },
  });
 
  useEffect(() => {
   
    
    player = ecs.createEntity(
      "player",
      [
        Pos(300, 200),
        Area(500, 100, 50, 50),
        Mass(0, 0),
     
      ]
    );
const goomba = ecs.createEntity(
      "goomaba",
      [
        Pos(500, 300),
        Area(500, 100, 50, 50),
        Mass(0, 0),
     
      ]
    );
    ecs.addEntity(player)
    ecs.addEntity(goomba)

  }, []);
`

///////////////////////===============================
  const createEntity = (
    name: string,
    components: EntityComponentType[],

  ): Entity => {

    
    let enitytName = name;
    const allComps: EntityComponentType[] = [];
    const allPros: Processors[] = [];
    for (let i = 0; i < components.length; i++) {
      allComps.push(components[i]);
    }
      
  

    return {
      name: enitytName,
      components: allComps,
      processors: allPros,
    };
  };

====================================
export type PositionState = {
  name: string;
  state: {
    x: SharedValue<number>;
    y: SharedValue<number>;
  }
  };
  
export type AreaState = {
  name: string;
  state: {
    width: SharedValue<number>;
    height: SharedValue<number>;
  }
  };
  
  export type SpriteState = {
    sprite: SharedValue<string>;
  };
  
export type MassState = {
  name: string;
  state: {
    mass?: SharedValue<number>;
    vX: SharedValue<number>;
    vY: SharedValue<number>;
  }
  };
  type EntityComponentType = PositionState | AreaState | MassState;

**Comment by Stuhl** [comment]
Thanks for the comment, can you edit your formatting? It looks a bit bad.

I'll add that as a discussion later on.

**Comment by mckeny3** [comment]
Apologies for the inconvenience. When I select the code option, it formats my code in an undesirable manner. Nevertheless, I am close to completing the development of a game engine similar to Kaboom. I have adopted a unique approach to the Entity Component System (ECS) architecture, where the systems contain the entities that they are responsible for.
